# This file created by conda-build 3.0.15+56.gd43c51d
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/idna-feedstock/recipe, last modified Wed Sep 20 04:39:57 2017
# ------------------------------------------------

package:
    name: idna
    version: '2.6'
source:
    fn: idna-2.6.tar.gz
    sha256: 2c6a5de3089009e3da7c5dde64a141dbc8551d5b7f6cf4ed7c2568d0cc520a8f
    url: https://pypi.io/packages/source/i/idna/idna-2.6.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h8628d0a_1
requirements:
    build:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - certifi 2017.7.27.1 py36hd973bb6_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 hd939716_3
        - ncurses 6.0 ha932d30_1
        - openssl 1.0.2l h57f3a61_2
        - python 3.6.2 hd750463_11
        - readline 7.0 h81b24a6_3
        - setuptools 36.2.2 py36ha346308_0
        - sqlite 3.20.1 h900c3b0_1
        - tk 8.6.7 hcdce994_1
        - xz 5.2.3 ha24016e_1
        - zlib 1.2.11 h60db283_1
    host:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - certifi 2017.7.27.1 py36hd973bb6_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 hd939716_3
        - ncurses 6.0 ha932d30_1
        - openssl 1.0.2l h57f3a61_2
        - python 3.6.2 hd750463_11
        - readline 7.0 h81b24a6_3
        - setuptools 36.2.2 py36ha346308_0
        - sqlite 3.20.1 h900c3b0_1
        - tk 8.6.7 hcdce994_1
        - xz 5.2.3 ha24016e_1
        - zlib 1.2.11 h60db283_1
    run:
        - python >=3.6,<3.7.0a0
test:
    imports:
        - idna
about:
    description: 'A library to support the Internationalised Domain Names in Applications

        (IDNA) protocol as specified in RFC 5891. This version of the protocol

        is often referred to as "IDNA2008".

        '
    dev_source: https://github.com/kjd/idna
    home: https://github.com/kjd/idna
    license: BSD Like
    license_file: LICENSE.rst
    summary: Internationalized Domain Names in Applications (IDNA).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - goanpeca
        - jschueller
        - mingwandroid
