# This file created by conda-build 3.0.15+56.gd43c51d
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/requests-feedstock/recipe, last modified Fri Sep 15 06:59:22 2017
# ------------------------------------------------

package:
    name: requests
    version: 2.18.4
source:
    sha256: 9c443e7324ba5b85070c4a818ade28bfabedf16ea10206da1132edaa6dda237e
    url: https://pypi.io/packages/source/r/requests/requests-2.18.4.tar.gz
build:
    number: '1'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py36h4516966_1
requirements:
    build:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - certifi 2017.7.27.1 py36hd973bb6_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 hd939716_3
        - ncurses 6.0 ha932d30_1
        - openssl 1.0.2l h57f3a61_2
        - python 3.6.2 hd750463_11
        - readline 7.0 h81b24a6_3
        - setuptools 36.2.2 py36ha346308_0
        - sqlite 3.20.1 h900c3b0_1
        - tk 8.6.7 hcdce994_1
        - xz 5.2.3 ha24016e_1
        - zlib 1.2.11 h60db283_1
    host:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - certifi 2017.7.27.1 py36hd973bb6_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 hd939716_3
        - ncurses 6.0 ha932d30_1
        - openssl 1.0.2l h57f3a61_2
        - python 3.6.2 hd750463_11
        - readline 7.0 h81b24a6_3
        - setuptools 36.2.2 py36ha346308_0
        - sqlite 3.20.1 h900c3b0_1
        - tk 8.6.7 hcdce994_1
        - xz 5.2.3 ha24016e_1
        - zlib 1.2.11 h60db283_1
    run:
        - certifi >=2017.4.17
        - chardet >=3.0.2,<3.1.0
        - idna >=2.5,<2.7
        - python >=3.6,<3.7.0a0
        - urllib3 >=1.21.1,<1.23
test:
    imports:
        - requests
about:
    description: 'Requests is the only Non-GMO HTTP library for Python, safe for human

        consumption.

        '
    dev_url: https://github.com/kennethreitz/requests
    doc_source_url: https://github.com/requests/requests/tree/master/docs
    doc_url: http://docs.python-requests.org/
    home: http://python-requests.org
    license: Apache 2.0
    license_file: LICENSE
    summary: Python HTTP for Humans.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - kalefranz
        - mcg1969
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
        - sigmavirus24
