# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/2c5246ec-2b17-479c-4836-e3b2ff51e3b6/volume/rsync-recipes/wheel-0.30.0-python3.6-on-osx, last modified Tue Nov 21 10:04:54 2017
# ------------------------------------------------

package:
    name: wheel
    version: 0.30.0
source:
    fn: wheel-0.30.0.tar.gz
    sha256: 9515fe0a94e823fd90b08d22de45d7bde57c90edce705b22f5e1ecf7e1b653c8
    url: https://pypi.io/packages/source/w/wheel/wheel-0.30.0.tar.gz
build:
    entry_points:
        - wheel=wheel.tool:main
    number: '1'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h5eb2c71_1
requirements:
    build:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - certifi 2017.7.27.1 py36hd973bb6_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.0 hd04f020_2
        - openssl 1.0.2m h86d3e6a_1
        - python 3.6.3 h5ce8c04_4
        - readline 7.0 hc1231fa_4
        - setuptools 36.5.0 py36h2134326_0
        - sqlite 3.20.1 h7e4c145_2
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.3 h0278029_2
        - zlib 1.2.11 hf3cbc9b_2
    host:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - certifi 2017.7.27.1 py36hd973bb6_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.0 hd04f020_2
        - openssl 1.0.2m h86d3e6a_1
        - python 3.6.3 h5ce8c04_4
        - readline 7.0 hc1231fa_4
        - setuptools 36.5.0 py36h2134326_0
        - sqlite 3.20.1 h7e4c145_2
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.3 h0278029_2
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - python >=3.6,<3.7.0a0
        - setuptools
about:
    home: https://bitbucket.org/pypa/wheel/
    license: MIT
    license_file: LICENSE.txt
    summary: A built-package format for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pelson
