# This file created by conda-build 3.1.6
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/a24aba61-7342-41ea-5869-d4ce6eb82e45/volume/rsync-recipes/conda-4.3.31-python3.6-on-osx-64, last modified Sat Dec 16 19:14:23 2017
# ------------------------------------------------

package:
    name: conda
    version: 4.3.31
source:
    fn: conda-4.3.31.tar.gz
    sha256: 70e1fdc5de7b552cd5695b82b672c59bab1251948856bac0dfd81e66eec59138
    url: https://github.com/conda/conda/archive/4.3.31.tar.gz
build:
    always_include_files:
        - bin/conda
        - bin/activate
        - bin/deactivate
    entry_points:
        - conda = conda.cli:main
        - conda-env = conda_env.cli.main:main
    number: '0'
    string: py36_0
requirements:
    build:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - libcxxabi 4.0.1 hebd6815_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.3 h0278029_2
        - yaml 0.1.7 hc338f04_2
        - zlib 1.2.11 hf3cbc9b_2
        - libcxx 4.0.1 h579ed51_0
        - openssl 1.0.2n hdbc3d79_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.0 hd04f020_2
        - libedit 3.1 hb4e282d_0
        - readline 7.0 hc1231fa_4
        - sqlite 3.20.1 h7e4c145_2
        - python 3.6.3 h47c878a_7
        - asn1crypto 0.23.0 py36h782d450_0
        - certifi 2017.11.5 py36ha569be9_0
        - chardet 3.0.4 py36h96c241c_1
        - idna 2.6 py36h8628d0a_1
        - pycosat 0.6.3 py36hee92d8f_0
        - pycparser 2.18 py36h724b2fc_1
        - pysocks 1.6.7 py36hfa33cec_1
        - ruamel_yaml 0.11.14 py36h9d7ade0_2
        - six 1.11.0 py36h0e22d5e_1
        - cffi 1.11.2 py36hd3e6348_0
        - cryptography 2.1.4 py36h842514c_0
        - pyopenssl 17.5.0 py36h51e4350_0
        - urllib3 1.22 py36h68b9469_0
        - requests 2.18.4 py36h4516966_1
    host:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - libcxxabi 4.0.1 hebd6815_0
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.3 h0278029_2
        - yaml 0.1.7 hc338f04_2
        - zlib 1.2.11 hf3cbc9b_2
        - libcxx 4.0.1 h579ed51_0
        - openssl 1.0.2n hdbc3d79_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.0 hd04f020_2
        - libedit 3.1 hb4e282d_0
        - readline 7.0 hc1231fa_4
        - sqlite 3.20.1 h7e4c145_2
        - python 3.6.3 h47c878a_7
        - asn1crypto 0.23.0 py36h782d450_0
        - certifi 2017.11.5 py36ha569be9_0
        - chardet 3.0.4 py36h96c241c_1
        - idna 2.6 py36h8628d0a_1
        - pycosat 0.6.3 py36hee92d8f_0
        - pycparser 2.18 py36h724b2fc_1
        - pysocks 1.6.7 py36hfa33cec_1
        - ruamel_yaml 0.11.14 py36h9d7ade0_2
        - six 1.11.0 py36h0e22d5e_1
        - cffi 1.11.2 py36hd3e6348_0
        - cryptography 2.1.4 py36h842514c_0
        - pyopenssl 17.5.0 py36h51e4350_0
        - urllib3 1.22 py36h68b9469_0
        - requests 2.18.4 py36h4516966_1
    run:
        - conda-env >=2.6
        - pycosat >=0.6.1
        - pyopenssl >=16.2.0
        - python >=3.6,<3.7.0a0
        - requests >=2.12.4
        - ruamel_yaml >=0.11.14
test:
    commands:
        - python -c "from __future__ import print_function; import conda; print(conda.__version__)"
        - which conda
        - which conda-env
        - conda --version
        - conda info
        - conda env --help
    imports:
        - conda
about:
    description: 'Conda is an open source package management system and environment

        management system for installing multiple versions of software packages

        and their dependencies and switching easily between them. It works on

        Linux, OS X and Windows, and was created for Python programs but can

        package and distribute any software.

        '
    dev_url: https://github.com/conda/conda
    doc_url: http://conda.pydata.org/docs/
    home: http://conda.pydata.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: OS-agnostic, system-level binary package and environment manager.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - kalefranz
        - mcg1969
        - mingwandroid
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
