python: '3.6'
numpy: '1.11'
perl: 5.22.2
lua: '5'
r_base: '3'
cpu_optimization_target: nocona
target_platform: osx-64
vendor: conda
build_platform: osx-64
cross_target_platform: osx-64
compiler_ver: 4.0.1
library_type: shared
zip_keys:
- !!python/tuple [FINAL_CPPFLAGS, FINAL_CFLAGS, FINAL_CXXFLAGS, FINAL_FFLAGS, FINAL_LDFLAGS,
  FINAL_DEBUG_CFLAGS, FINAL_DEBUG_CXXFLAGS, FINAL_DEBUG_FFLAGS]
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
FINAL_CPPFLAGS: -D_FORTIFY_SOURCE=2
FINAL_CXXFLAGS: -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona
  -mtune=haswell -ftree-vectorize -mmacosx-version-min=10.9 -Wl,-headerpad_max_install_names
  -fPIC -fstack-protector-strong -O2 -pipe
FINAL_LDFLAGS: -Wl,-headerpad_max_install_names -Wl,-O2,--sort-common,--as-needed,-z,relro
FINAL_DEBUG_FFLAGS: -fopenmp -march=nocona -mtune=core2 -ftree-vectorize -mmacosx-version-min=10.9
  -Wl,-headerpad_max_install_names -fPIC -fstack-protector -O2 -pipe -Og -g -Wall
  -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
FINAL_DEBUG_CFLAGS: -march=nocona -mtune=haswell -ftree-vectorize -mmacosx-version-min=10.9
  -Wl,-headerpad_max_install_names -fPIC -fstack-protector-strong -O2 -pipe -Og -g
  -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
FINAL_DEBUG_CXXFLAGS: -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona
  -mtune=haswell -ftree-vectorize -mmacosx-version-min=10.9 -Wl,-headerpad_max_install_names
  -fPIC -fstack-protector-strong -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace
  -fimplicit-none -fvar-tracking-assignments
FINAL_FFLAGS: -fopenmp -march=nocona -mtune=core2 -ftree-vectorize -mmacosx-version-min=10.9
  -Wl,-headerpad_max_install_names -fPIC -fstack-protector -O2 -pipe
FINAL_CFLAGS: -march=nocona -mtune=haswell -ftree-vectorize -mmacosx-version-min=10.9
  -Wl,-headerpad_max_install_names -fPIC -fstack-protector-strong -O2 -pipe
