# This file created by conda-build 3.0.27
# meta.yaml template originally from:
# /opt/concourse/worker/volumes/live/35b93f0c-a307-40ab-5164-b70edbd6ec97/volume/rsync-recipes/pip-9.0.1-python3.6-on-osx, last modified Tue Oct 24 09:24:47 2017
# ------------------------------------------------

package:
    name: pip
    version: 9.0.1
source:
    fn: pip-9.0.1.tar.gz
    sha256: 09f243e1a7b461f654c26a725fa373211bb7ff17a9300058b205c61658ca940d
    url: https://pypi.io/packages/source/p/pip/pip-9.0.1.tar.gz
build:
    disable_pip: 'True'
    entry_points:
        - pip = pip:main
    number: '4'
    string: py36h1555ced_4
requirements:
    build:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - certifi 2017.7.27.1 py36hd973bb6_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 hd939716_3
        - ncurses 6.0 ha932d30_1
        - openssl 1.0.2l h57f3a61_2
        - python 3.6.3 h6804ab2_0
        - readline 7.0 h81b24a6_3
        - setuptools 36.5.0 py36h2134326_0
        - sqlite 3.20.1 h900c3b0_1
        - tk 8.6.7 hcdce994_1
        - xz 5.2.3 ha24016e_1
        - zlib 1.2.11 h60db283_1
    host:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - certifi 2017.7.27.1 py36hd973bb6_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 hd939716_3
        - ncurses 6.0 ha932d30_1
        - openssl 1.0.2l h57f3a61_2
        - python 3.6.3 h6804ab2_0
        - readline 7.0 h81b24a6_3
        - setuptools 36.5.0 py36h2134326_0
        - sqlite 3.20.1 h900c3b0_1
        - tk 8.6.7 hcdce994_1
        - xz 5.2.3 ha24016e_1
        - zlib 1.2.11 h60db283_1
    run:
        - python >=3.6,<3.7.0a0
        - setuptools
        - wheel
test:
    commands:
        - pip -h
        - pip list
    imports:
        - pip
about:
    dev_url: https://github.com/pypa/pip
    doc_url: https://pip.pypa.io/en/stable/
    home: https://pip.pypa.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: PyPA recommended tool for installing Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
