# This file created by conda-build 3.0.15+56.gd43c51d
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/urllib3-feedstock/recipe, last modified Mon Sep 11 14:11:45 2017
# ------------------------------------------------

package:
    name: urllib3
    version: '1.22'
source:
    fn: urllib3-1.22.tar.gz
    sha256: cc44da8e1145637334317feebd728bd869a35285b93cbb4cca2577da7e62db4f
    url: https://pypi.io/packages/source/u/urllib3/urllib3-1.22.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h68b9469_0
requirements:
    build:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - certifi 2017.7.27.1 py36hd973bb6_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 hd939716_3
        - ncurses 6.0 ha932d30_1
        - openssl 1.0.2l h57f3a61_2
        - python 3.6.2 hd750463_11
        - readline 7.0 h81b24a6_3
        - setuptools 36.2.2 py36ha346308_0
        - sqlite 3.20.1 h900c3b0_1
        - tk 8.6.7 hcdce994_1
        - xz 5.2.3 ha24016e_1
        - zlib 1.2.11 h60db283_1
    host:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - certifi 2017.7.27.1 py36hd973bb6_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 hd939716_3
        - ncurses 6.0 ha932d30_1
        - openssl 1.0.2l h57f3a61_2
        - python 3.6.2 hd750463_11
        - readline 7.0 h81b24a6_3
        - setuptools 36.2.2 py36ha346308_0
        - sqlite 3.20.1 h900c3b0_1
        - tk 8.6.7 hcdce994_1
        - xz 5.2.3 ha24016e_1
        - zlib 1.2.11 h60db283_1
    run:
        - certifi
        - cryptography >=1.3.4
        - idna >=2.0.0
        - pyopenssl >=0.14
        - pysocks >=1.5.6,<2.0,!=1.5.7
        - python >=3.6,<3.7.0a0
test:
    imports:
        - urllib3
        - urllib3.contrib
        - urllib3.packages
        - urllib3.packages.backports
        - urllib3.packages.ssl_match_hostname
        - urllib3.util
about:
    description: 'urllib3 is a powerful, sanity-friendly HTTP client for Python. Much
        of the

        Python ecosystem already uses urllib3. urllib3 brings many critical features

        that are missing from the Python standard libraries, such as thread safety,

        connection pooling, client side ssl/tls verification, support for gzip and

        deflate encodings, HTTP and SOCKS proxy support, helpers for retrying requests

        and dealing with HTTP redirects.

        '
    dev_url: https://github.com/shazow/urllib3
    doc_source_url: https://github.com/shazow/urllib3/tree/master/docs
    doc_url: https://urllib3.readthedocs.io/
    home: https://urllib3.readthedocs.io/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: HTTP library with thread-safe connection pooling, file post, and more.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pmlandwehr
        - sigmavirus24
