# This file created by conda-build 3.0.15+148.g91b57bf
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/python.app-feedstock/recipe, last modified Thu Oct 26 08:51:06 2017
# ------------------------------------------------

package:
    name: python.app
    version: '2'
build:
    number: '7'
    string: py36h54569d5_7
requirements:
    build:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 hd939716_3
        - ncurses 6.0 ha932d30_1
        - openssl 1.0.2l h57f3a61_2
        - python 3.6.3 h6804ab2_0
        - readline 7.0 h81b24a6_3
        - sqlite 3.20.1 h900c3b0_1
        - tk 8.6.7 hcdce994_1
        - xz 5.2.3 ha24016e_1
        - zlib 1.2.11 h60db283_1
    run:
        - python >=3.6,<3.7.0a0
test:
    commands:
        - python.app -V
        - pythonw -V
    files:
        - t.py
about:
    license: BSD
    summary: Proxy on OS X letting Python libraries hook into the gui event loop
extra:
    copy_test_source_files: true
    final: true
