# This file created by conda-build 3.0.31
# meta.yaml template originally from:
# /opt/concourse/volumes/live/faecf62b-c160-4bc5-6d0a-ca18b5bff0ef/volume/rsync-recipes/cryptography-2.1.4-python3.6-on-nwani-osx-64, last modified Sat Dec  2 01:34:40 2017
# ------------------------------------------------

package:
    name: cryptography
    version: 2.1.4
source:
    fn: cryptography-2.1.4.tar.gz
    sha256: e4d967371c5b6b2e67855066471d844c5d52d210c36c28d49a8507b96e2c5291
    url: https://pypi.io/packages/source/c/cryptography/cryptography-2.1.4.tar.gz
build:
    number: '0'
    script:
        - export CFLAGS="-I${PREFIX}/include ${CFLAGS}"
        - export LDFLAGS="-L${PREFIX}/lib ${LDFLAGS}"
        - python setup.py install --single-version-externally-managed --record=record.txt
    string: py36h842514c_0
requirements:
    build:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - cctools 895 h7512d6f_0
        - certifi 2017.11.5 py36ha569be9_0
        - cffi 1.11.2 py36hd3e6348_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h9d74b7d_5
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 h475c297_4
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
        - ncurses 6.0 hd04f020_2
        - openssl 1.0.2m h86d3e6a_1
        - pip 9.0.1 py36h1555ced_4
        - pycparser 2.18 py36h724b2fc_1
        - python 3.6.3 h5ce8c04_4
        - readline 7.0 hc1231fa_4
        - setuptools 36.5.0 py36h2134326_0
        - sqlite 3.20.1 h7e4c145_2
        - tk 8.6.7 h35a86e2_3
        - wheel 0.30.0 py36h5eb2c71_1
        - xz 5.2.3 h0278029_2
        - zlib 1.2.11 hf3cbc9b_2
    host:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - certifi 2017.11.5 py36ha569be9_0
        - cffi 1.11.2 py36hd3e6348_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.0 hd04f020_2
        - openssl 1.0.2m h86d3e6a_1
        - pip 9.0.1 py36h1555ced_4
        - pycparser 2.18 py36h724b2fc_1
        - python 3.6.3 h5ce8c04_4
        - readline 7.0 hc1231fa_4
        - setuptools 36.5.0 py36h2134326_0
        - sqlite 3.20.1 h7e4c145_2
        - tk 8.6.7 h35a86e2_3
        - wheel 0.30.0 py36h5eb2c71_1
        - xz 5.2.3 h0278029_2
        - zlib 1.2.11 hf3cbc9b_2
    run:
        - asn1crypto >=0.21.0
        - cffi >=1.7
        - idna >=2.1
        - openssl 1.0.*
        - openssl >=1.0.2m,<1.0.3a
        - python >=3.6,<3.7.0a0
        - six >=1.4.1
test:
    commands:
        - pytest
    imports:
        - cryptography
        - cryptography.fernet
        - cryptography.hazmat
        - cryptography.hazmat.backends
        - cryptography.hazmat.backends.openssl
        - cryptography.hazmat.bindings
        - cryptography.hazmat.bindings.openssl
        - cryptography.hazmat.primitives
        - cryptography.hazmat.primitives.asymmetric
        - cryptography.hazmat.primitives.ciphers
        - cryptography.hazmat.primitives.kdf
        - cryptography.hazmat.primitives.twofactor
        - cryptography.x509
    requires:
        - cryptography-vectors 2.1.4.*
        - hypothesis >=1.11.4
        - iso8601
        - pretend
        - pytest >=3.2.1,!=3.3.0
        - pytz
    source_files:
        - tests
about:
    description: 'Cryptography is a package which provides cryptographic recipes and

        primitives to Python developers. Our goal is for it to be your

        "cryptographic standard library". It supports Python 2.6-2.7, Python 3.3+,

        and PyPy 2.6+. Cryptography includes both high level recipes, and low level

        interfaces to common cryptographic algorithms such as symmetric ciphers,

        message digests and key derivation functions.

        '
    dev_url: https://github.com/pyca/cryptography
    doc_source_url: https://github.com/pyca/cryptography/tree/master/docs
    doc_url: http://cryptography.readthedocs.io/
    home: https://github.com/pyca/cryptography
    license: Apache 2.0 or BSD 3-Clause, PSF 2
    license_family: BSD
    license_file: LICENSE
    summary: Provides cryptographic recipes and primitives to Python developers
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jschueller
        - mingwandroid
